In [1]:
from unittest import result

import pandas as pd
import numpy as np
import re
import unicodedata
from PIL.ImagePath import Path
from narwhals import group_by

from pandas.core.computation.parsing import tokenize_string

FILENAME = "F:/Milestone 2/sampleddata.csv"

In [ ]:

df = pd.read_csv(FILENAME)

df

In [ ]:
df = df.replace(r'\xa0', ' ', regex=True)
en = df[df['lang'] == 'en']
en

In [ ]:
def clean_tweet(df):
    df['cleanedTweet'] = df['rawContent'].str.normalize('NFKD')
    df['cleanedTweet'] = df['cleanedTweet'].astype(str).str.replace(r'(\n)', lambda m: "",regex=True).str.strip()
    df['cleanedTweet'] = df['cleanedTweet'].str.replace(r"^.{0,5}(@\S*\b\s)+|(https:\S*\b)",lambda m: "",regex=True)
    df['cleanedTweet'] = df['cleanedTweet'].str.replace(r'\s+', ' ', regex=True)
    return df

clean_tweet(en)

In [ ]:
explosion = en.explode('mentionedUsers').reset_index(drop=True)
dict_series = explosion['mentionedUsers'].apply(lambda x: x if isinstance(x, list) else {})
normed = pd.json_normalize(dict_series)
#result = pd.concat([explosion['id'], normed[['name','screen_name']]], axis=1)
#result
explosion

In [ ]:
import ast
#en['mentionedUsers'] = en['mentionedUsers'].apply(lambda x: ast.literal_eval(x))
# 1. Explode the list (missing rows are safely kept as NaN)
exploded_df = en.explode('mentionedUsers').reset_index(drop=True)

# 2. Fill NaN rows with an empty dict so json_normalize doesn't fail
dict_series = exploded_df['mentionedUsers'].apply(lambda x: x if isinstance(x, dict) else {})

# 3. Normalize the dictionaries into columns
normalized_cols = pd.json_normalize(dict_series)

# 4. Combine the ID with the extracted values
result = pd.concat([exploded_df['id'], normalized_cols[['name', 'screen_name']]], axis=1)

users = result.groupby(['screen_name','name']).agg(count =('screen_name','size'))
users

In [ ]:
pd.read_csv("../DataFiles/combined_output.csv")

In [ ]:
pd.read_csv("../fixed/octobergap_chunk_14.csv")

In [ ]:
pd.read_csv("../x-24-us-election/part_47/octobergap_chunk_41.csv.gz")

In [ ]:
df[df['retweetedTweet'] == True]

In [ ]:
octber = pd.read_csv('../x-24-us-election/part_19/may_july_chunk_380.csv.gz', low_memory=False)

In [ ]:
octber['date'] = pd.to_datetime(octber['date'])
min_rows = octber[octber['date'] == octber['date'].min()]

In [ ]:
min_rows

In [ ]:
octber

In [ ]:
octber[octber['retweetedTweet'] == '1811339675384357201']

In [ ]:
df2 = pd.read_csv("F:/Milestone 2/raw_sample_data.csv")
df2['date']

In [ ]:
df3 = pd.read_csv("F:/Milestone 2/sampleddata.csv")
combined = df3.groupby("week").agg(
    min_date = ('date', 'min'),
    max_date = ('date', 'max')
)
date_cols = ['min_date', 'max_date']
combined[date_cols] = combined[date_cols].apply(pd.to_datetime)
combined[date_cols] = combined[date_cols].apply(lambda x: x.dt.strftime('%B %d'))
combined['week_range'] = combined['min_date'].astype(str).str.cat(combined['max_date'].astype(str), sep=' - ', na_rep='')
combined.to_csv('weeks_table.csv')

In [3]:
pd.set_option('display.float_format', lambda x: f'{x:.1f}')

df4 = pd.read_csv("F:/Milestone 2/sampleddata.csv")
#df4 = df4.drop_duplicates(subset='id', keep='first')
#df4.to_csv("F:/Milestone 2/sampleddata.csv")
#df4[df4['rawContent'].str.startswith('RT@', na=False)]
df4

,id,text,epoch,media,retweetedTweet,lang,rawContent,replyCount,retweetCount,likeCount,...,mentionedUsers,links,viewCount,quotedTweet,in_reply_to_screen_name,location,user,date,week,cleanedTweet
0,1801020560257728768.0,They know November is lost #Trump2024,1718231737.0,[],False,en,They know November is lost #Trump2024,0.0,0.0,0.0,...,[],[],"{'count': '7', 'state': 'EnabledWithCount'}",True,NaN,NaN,"{'id': 1778002910778937344, 'id_str': '1778002...",2024-06-12,6,They know November is lost #Trump2024
1,1801012950645301248.0,@Strandjunker Blame Biden they said.\n\nThat’s...,1718229923.0,[],False,en,@Strandjunker Blame Biden they said.\n\nThat’s...,1.0,0.0,0.0,...,"[{'id_str': '1866938882', 'name': 'Andrea Junk...",[],"{'count': '87', 'state': 'EnabledWithCount'}",False,Strandjunker,NaN,"{'id': 1426194752353882112, 'id_str': '1426194...",2024-06-12,6,Blame Biden they said.That’s what they keep sa...
2,1801011133219803136.0,"@letitflye There are no Biden rooters, only Tr...",1718229489.0,[],False,en,"@letitflye There are no Biden rooters, only Tr...",1.0,0.0,1.0,...,"[{'id_str': '3429214941', 'name': 'mark lye', ...",[],"{'count': '36', 'state': 'EnabledWithCount'}",False,letitflye,NaN,"{'id': 2214303692, 'id_str': '2214303692', 'ur...",2024-06-12,6,"There are no Biden rooters, only Trump haters"
3,1801008723365708032.0,@Fernand46357857 You must be thinking of Joe B...,1718228915.0,[],False,en,@Fernand46357857 You must be thinking of Joe B...,0.0,0.0,0.0,...,"[{'id_str': '1244663153872560129', 'name': 'Fe...",[],"{'count': '4', 'state': 'EnabledWithCount'}",False,Fernand46357857,NaN,"{'id': 1002946962251972609, 'id_str': '1002946...",2024-06-12,6,You must be thinking of Joe Biden - the guy th...
4,1801020603375476992.0,.@NicolleDWallace @DeadlineWH: I watched your ...,1718231747.0,[],False,en,.@NicolleDWallace @DeadlineWH: I watched your ...,1.0,0.0,2.0,...,"[{'id_str': '860555190', 'name': 'Nicolle Wall...",[],"{'count': '90', 'state': 'EnabledWithCount'}",False,NaN,NaN,"{'id': 716784391553359872, 'id_str': '71678439...",2024-06-12,6,@DeadlineWH: I watched your show today as you ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26063,1813665624289432064.0,"""Biden-⁠Harris Administration Announces New A...",1721246555.0,[],False,en,"""Biden-⁠Harris Administration Announces New A...",0.0,0.0,0.0,...,[],[{'display_url': 'whitehouse.gov/briefing-room...,"{'count': '34', 'state': 'EnabledWithCount'}",False,NaN,NaN,"{'id': 821458719196090368, 'id_str': '82145871...",2024-07-17,11,"""Biden-⁠Harris Administration Announces New Ac..."
26064,1813680747015741696.0,@Dylanmooersr @matthewstoller Interesting idea...,1721250161.0,[],False,en,@Dylanmooersr @matthewstoller Interesting idea...,1.0,0.0,0.0,...,"[{'id_str': '2030711', 'name': 'Matt Stoller',...",[],"{'count': '17', 'state': 'EnabledWithCount'}",False,dmoersr,NaN,"{'id': 1177775343836508161, 'id_str': '1177775...",2024-07-17,11,Interesting idea that if Trump was gone it wou...
26065,1813663258584473600.0,RNC night one ratings down 5 million viewers c...,1721245991.0,[],False,en,RNC night one ratings down 5 million viewers c...,0.0,0.0,0.0,...,[],[{'display_url': 'independent.co.uk/news/world...,"{'count': '24', 'state': 'EnabledWithCount'}",False,NaN,NaN,"{'id': 434453011, 'id_str': '434453011', 'url'...",2024-07-17,11,RNC night one ratings down 5 million viewers c...
26066,1813676839698563072.0,@e2dbg @BillKristol Are you on drugs?\nThose f...,1721249229.0,[],False,en,@e2dbg @BillKristol Are you on drugs?\nThose f...,4.0,0.0,0.0,...,"[{'id_str': '2842833556', 'name': 'justsayin',...",[],"{'count': '29', 'state': 'EnabledWithCount'}",False,e2dbg,NaN,"{'id': 1084047812772413440, 'id_str': '1084047...",2024-07-17,11,Are you on drugs?Those facts have litterly bee...
26067,1813680476391191296.0,"@medeabenjamin So protestors, nonRNC invitees ...",1721250096.0,[],False,en,"@medeabenjamin So protestors, nonRNC invitees ...",0.0,0.0,0.0,...,"[{'id_str': '14930580', 'name': 'Medea Benjami...",[],"{'count': '55', 'state': 'EnabledWithCount'}",False,medeabenjamin,NaN,"{'id': 150620364, 'id_str': '150620364', 'url'...",2024-07-17,11,"So protestors, nonRNC invitees block entrance ..."

In [5]:
sanity = pd.read_csv("F:/Milestone 2/x-24-us-election/part_45/octobergap_chunk_3.csv.gz")
sanity

,type,id,username,text,url,epoch,id_str,lang,rawContent,replyCount,...,sourceUrl,sourceLabel,media,card,cashtags,viewCount,place,user,epoch_dt,date
0,tweet-,1843003392605790603,Max01144337,@Alphafox78 She’s not a kid. She’s a full grow...,https://twitter.com/Max01144337/status/1843003...,1728241224,1843003392605790603,en,@Alphafox78 She’s not a kid. She’s a full grow...,0,...,PW,PW,PW,PW,PW,PW,PW,"{'id': 1196130378681143296, 'id_str': '1196130...",2024-10-06 19:00:24,2024-10-06
1,tweet-,1843003391313883198,cue_bono,@SikanderDh85907 @silentnomore12 @MattScottMus...,https://twitter.com/cue_bono/status/1843003391...,1728241224,1843003391313883198,qme,@SikanderDh85907 @silentnomore12 @MattScottMus...,1,...,PW,PW,PW,PW,PW,PW,PW,"{'id': 911647273477640192, 'id_str': '91164727...",2024-10-06 19:00:24,2024-10-06
2,tweet-,1843003383843840345,forzadraghi,@UGirovago77000 Ma se non ha il coraggio di di...,https://twitter.com/forzadraghi/status/1843003...,1728241222,1843003383843840345,it,@UGirovago77000 Ma se non ha il coraggio di di...,0,...,PW,PW,PW,PW,PW,PW,PW,"{'id': 1374984048, 'id_str': '1374984048', 'ur...",2024-10-06 19:00:22,2024-10-06
3,tweet-,1843003383663476967,yoyotabby,@YoungDeplorable @DC_Draino Biden/Harris/Democ...,https://twitter.com/yoyotabby/status/184300338...,1728241222,1843003383663476967,en,@YoungDeplorable @DC_Draino Biden/Harris/Democ...,0,...,PW,PW,PW,PW,PW,PW,PW,"{'id': 1268962003642494977, 'id_str': '1268962...",2024-10-06 19:00:22,2024-10-06
4,tweet-,1843003379704074263,SMunnelley,"@B4ckBL4ck3CI So is trump , so is biden , all ...",https://twitter.com/SMunnelley/status/18430033...,1728241221,1843003379704074263,en,"@B4ckBL4ck3CI So is trump , so is biden , all ...",1,...,PW,PW,PW,PW,PW,PW,PW,"{'id': 1596157426016870400, 'id_str': '1596157...",2024-10-06 19:00:21,2024-10-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,tweet-,1844890509246070952,MAGAWoodworker,@HavasuMarena Chum,https://twitter.com/MAGAWoodworker/status/1844...,1728691148,1844890509246070952,en,@HavasuMarena Chum,0,...,PW,PW,PW,PW,PW,PW,PW,"{'id': 1206753515109933056, 'id_str': '1206753...",2024-10-11 23:59:08,2024-10-11
49996,tweet-,1844890505177595990,KelliBretzke,@Eb67735B @TJLakers01 @PURE_BL00D2 @PSwal807 @...,https://twitter.com/KelliBretzke/status/184489...,1728691147,1844890505177595990,qme,@Eb67735B @TJLakers01 @PURE_BL00D2 @PSwal807 @...,0,...,PW,PW,PW,PW,PW,PW,PW,"{'id': 1482853672342147072, 'id_str': '1482853...",2024-10-11 23:59:07,2024-10-11
49997,tweet-,1844890504091271193,Mr_PinkEyez,@ValentinaForUSA @realDonaldTrump Yes! \n\nThe...,https://twitter.com/Mr_PinkEyez/status/1844890...,1728691147,1844890504091271193,en,@ValentinaForUSA @realDonaldTrump Yes! \n\nThe...,0,...,PW,PW,PW,PW,PW,PW,PW,"{'id': 1734382453425328128, 'id_str': '1734382...",2024-10-11 23:59:07,2024-10-11
49998,tweet-,1844890503550206209,chrishbenge,Trump Goes Dark MAGA and Calls Harris ‘Threat ...,https://twitter.com/chrishbenge/status/1844890...,1728691147,1844890503550206209,en,Trump Goes Dark MAGA and Calls Harris ‘Threat ...,0,...,PW,PW,PW,PW,PW,PW,PW,"{'id': 22820478, 'id_str': '22820478', 'url': ...",2024-10-11 23:59:07,2024-10-11
49999,tweet-,1844890502354829797,Jennife56206694,"Exactly. Is that OK with you, Black MAGA's?",https://twitter.com/Jennife56206694/status/184...,1728691146,1844890502354829797,en,"Exactly. Is that OK with you, Black MAGA's?",0,...,PW,PW,PW,PW,PW,PW,PW,"{'id': 1603809659298938880, 'id_str': '1603809...",2024-10-11 23:59:06,2024-10-11

In [6]:
ughhh = pd.read_parquet('F:/Milestone 2/sampleddata.parquet')
ughhh.columns

Index(['tweet_id', 'text', 'media', 'retweetedTweet', 'lang', 'rawContent',
       'replyCount', 'retweetCount', 'likeCount', 'quoteCount', 'hashtags',
       'mentionedUsers', 'links', 'viewCount', 'quotedTweet',
       'in_reply_to_screen_name', 'location', 'user', 'date', 'week',
       'cleanedTweet'],
      dtype='str')

In [7]:
ughhh

,tweet_id,text,media,retweetedTweet,lang,rawContent,replyCount,retweetCount,likeCount,quoteCount,...,mentionedUsers,links,viewCount,quotedTweet,in_reply_to_screen_name,location,user,date,week,cleanedTweet
0,1822052939076141150,"Read ""Conservative warns MAGA fans Trump 'coul...",[],False,en,"Read ""Conservative warns MAGA fans Trump 'coul...",0.0,0.0,0.0,0.0,...,[],[{'display_url': 'l.smartnews.com/p-rbqCZ/22rm...,"{'count': '4', 'state': 'EnabledWithCount'}",False,NaN,NaN,"{'id': 1441751938719121415, 'id_str': '1441751...",2024-08-09,14,"Read ""Conservative warns MAGA fans Trump 'coul..."
1,1822044941042004254,"@lululuvshollis Well, all the millionaires you...",[],False,en,"@lululuvshollis Well, all the millionaires you...",0.0,0.0,0.0,0.0,...,"[{'id_str': '824312677904351238', 'name': 'LuL...",[],"{'count': '4', 'state': 'EnabledWithCount'}",False,lululuvshollis,NaN,"{'id': 1507732343427002373, 'id_str': '1507732...",2024-08-09,14,"Well, all the millionaires you’re referring to..."
2,1822032912381776359,@gatewaypundit That ahhhh…..that’s not legal. ...,[],False,en,@gatewaypundit That ahhhh…..that’s not legal. ...,0.0,1.0,25.0,0.0,...,"[{'id_str': '19211550', 'name': 'The Gateway P...",[],"{'count': '739', 'state': 'EnabledWithCount'}",False,gatewaypundit,NaN,"{'id': 35338824, 'id_str': '35338824', 'url': ...",2024-08-09,14,That ahhhh.....that’s not legal. Which SS offi...
3,1822041814712643713,@SUENUTTER115928 @its_The_Dr I see the sign sa...,[],False,en,@SUENUTTER115928 @its_The_Dr I see the sign sa...,2.0,0.0,1.0,0.0,...,"[{'id_str': '1751057710299160576', 'name': '🇺🇸...",[],"{'count': '12', 'state': 'EnabledWithCount'}",False,SUENUTTER115928,NaN,"{'id': 1352623760365375491, 'id_str': '1352623...",2024-08-09,14,I see the sign says Biden 2020. The picture wa...
4,1822044641534849202,@EdKrassen Why is Ed so obsessed with Donald T...,[],False,en,@EdKrassen Why is Ed so obsessed with Donald T...,0.0,0.0,0.0,0.0,...,"[{'id_str': '132339474', 'name': 'Ed Krassenst...",[],"{'count': '6', 'state': 'EnabledWithCount'}",False,EdKrassen,NaN,"{'id': 1336456304089559041, 'id_str': '1336456...",2024-08-09,14,Why is Ed so obsessed with Donald Trump?
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465141,1834540285633740969,@Be20608Routine @eastbengal_fc @THE_RanjitBaja...,[],False,en,@Be20608Routine @eastbengal_fc @THE_RanjitBaja...,1.0,0.0,0.0,0.0,...,"[{'id_str': '1788564885951205376', 'name': 'Be...",[],"{'count': '122', 'state': 'EnabledWithCount'}",False,Be20608Routine,NaN,"{'id': 1659950839426068483, 'id_str': '1659950...",2024-09-13,19,Will not the involvement of DC be considered a...
465142,1834608756325294197,@PedestrianTakes The left is too small for AOC...,[],False,en,@PedestrianTakes The left is too small for AOC...,0.0,0.0,3.0,0.0,...,"[{'id_str': '1295256696932139010', 'name': 'Ry...",[],"{'count': '124', 'state': 'EnabledWithCount'}",False,Jaytingwalker,NaN,"{'id': 56028869, 'id_str': '56028869', 'url': ...",2024-09-13,19,The left is too small for AOC fans to cut out ...
465143,1834554225201680429,How can Kamala Harris even show her face in pu...,[],False,en,How can Kamala Harris even show her face in pu...,0.0,1.0,2.0,0.0,...,[],[],"{'count': '93', 'state': 'EnabledWithCount'}",True,NaN,NaN,"{'id': 1711715133007781888, 'id_str': '1711715...",2024-09-13,19,How can Kamala Harris even show her face in pu...
465144,1834618723107484156,@yashar John legend is a dnc shill and his wif...,[],False,en,@yashar John legend is a dnc shill and his wif...,0.0,0.0,0.0,0.0,...,"[{'id_str': '11744152', 'name': 'Yashar Ali 🐘'...",[],"{'count': '9', 'state': 'EnabledWithCount'}",False,yashar,NaN,"{'id': 1521889480474562562, 'id_str': '1521889...",2024-09-13,19,John legend is a dnc shill and his wife is vil...
465145,1834620327608844611,@franklinisbored @KamalaHarris @TheDemocrats h...,[],False,en,@franklinisbored @KamalaHarris @TheDemocrats h...,1.0,1.0,11.0,0.0,...,"[{'id_str': '1323747353308835840', 'name': 'Fr...","[{'display_url': 'x.com/kylenabecker/s…', 'exp...","{'count': '114', 'state': 'EnabledWithCount'}",True,franklinisbored,NaN,"{'id': 1442937071317000192, 'id_str': '1442937...",2024-09-13,19,about Harris is fake

In [17]:
#checking = pd.read_csv("F:/Milestone 2/exemplar_file.csv")
#checking.columns
idk = pd.read_csv("F:/Milestone 2/sampleddate.csv",nrows=1)
idk.columns

Index(['tweet_id', 'text', 'epoch', 'media', 'retweetedTweet', 'lang',
       'rawContent', 'replyCount', 'retweetCount', 'likeCount', 'quoteCount',
       'hashtags', 'mentionedUsers', 'links', 'viewCount', 'quotedTweet',
       'in_reply_to_screen_name', 'location', 'user', 'date', 'week',
       'cleanedTweet'],
      dtype='str')

In [4]:
df = pd.read_csv("F:/Milestone 2/weekly_orig_totals.csv")
df['chunk_sample'] = round(15000 / df['weekly_orig_total'],4)
df.to_csv("F:/Milestone 2/weekly_orig_totals.csv")